import type { Metadata } from "next";
import "../../styles/globals.css";
import localFont from "next/font/local";
import TopNavigation from "@/components/navigation/TopNavigation";
import Footer from "@/components/Footer";
import { DEFAULT_ALIGNMENT } from "@/constants";

const satoshiFont = localFont({
  src: "../../../public/satoshi/Satoshi-Variable.woff2",
});

export const metadata: Metadata = {
  title: "Lucca Romaniello",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* // TODO:  FIX NAVBAR MOVING WHEN CHANGING BETWEEN MAIN TABS */}
      <body
        className={`${satoshiFont.className} ${DEFAULT_ALIGNMENT} items-center`}
      >
        <TopNavigation />
        <div className="flex flex-col">
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
