import type { Metadata } from "next";
import "../../styles/globals.css";
import localFont from 'next/font/local';
import TopNavigation from "@/components/navigation/TopNavigation";
import Footer from "@/components/Footer";

const satoshiFont = localFont({
  src: '../../../public/satoshi/Satoshi-Variable.woff2',
});

export const metadata: Metadata = {
  title: "Lucca Romaniello",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {/* // TODO:  FIX NAVBAR MOVING WHEN CHANGING BETWEEN MAIN TABS */}
      <body className={`${satoshiFont.className} flex flex-col items-center px-6 lg:px-56 2xl:px-96`}>
        <TopNavigation />
        <div className="flex flex-col">
          <main>
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}