import { Metadata } from "next";
import "../../styles/globals.css";

export const metadata: Metadata = {
  title: "Lucca Romaniello — Ânima Educação ",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  }
};

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col items-center`}>
        {children}
      </body>
    </html>
  )
}
