import { Metadata } from "next";
import "../../styles/globals.css";
import TopNavigation from "@/components/navigation/TopNavigation";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Lucca Romaniello — Ânima Educação ",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  }
};

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col items-center`}>
        <div className="w-full px-6 lg:px-56 2xl:px-96">
          <TopNavigation />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
