import type { Metadata } from "next";
import "../styles/globals.css";
import localFont from 'next/font/local';
import TopNavigation from "@/components/navigation/TopNavigation";
import SideNavigation from "@/components/navigation/SideNavigation";
import About from "./about/page";
import AnimaEducacao from "./design/anima-educacao/page";
import Footer from "@/components/Footer";

const satoshiFont = localFont({
  src: '../../public/satoshi/Satoshi-Variable.woff2',
});

export const metadata: Metadata = {
  title: "Lucca Romaniello",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.className} flex flex-col items-center px-6 lg:px-56 xl:px-64 2xl:px-96`}>
        <TopNavigation />
        <div className="flex flex-col">
          <main>
            {children}
          </main>
        </div>
        <Footer />
      </body>
      {/* 2xl:px-96 xl:px-64 lg:px-56 */}
    </html>
  );
}