import type { Metadata } from "next";
import "../styles/globals.css";
import localFont from 'next/font/local';
import TopNavigation from "@/components/TopNavigation";
import SideNavigation from "@/components/SideNavigation";

const satoshiFont = localFont({
  src: '../../public/satoshi/Satoshi-Variable.woff2',
});

export const metadata: Metadata = {
  title: "Lucca Romaniello",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.className} flex flex-col gap-16 px-80 py-8 h-screen`}>
        <TopNavigation />
        <div className="grid grid-cols-[600px_1fr] h-full">
          <SideNavigation />
          {children}
        </div>
      </body>
    </html>
  );
}
