import type { Metadata } from "next";
import "../styles/globals.css";
import localFont from 'next/font/local';
import TopNavigation from "@/components/TopNavigation";
import SideNavigation from "@/components/SideNavigation";
import About from "./about/page";
import AnimaEducacao from "./design/anima-educacao/page";

const satoshiFont = localFont({
  src: '../../public/satoshi/Satoshi-Variable.woff2',
});

export const metadata: Metadata = {
  title: "Lucca Romaniello",
  description: "Generated by create next app",
  icons: {
    icon: "/lucca-icon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.className} flex flex-col 2xl:gap-16 xl:gap-4 h-screen 2xl:px-64 xl:px-20 py-24`}>
        {/* <TopNavigation /> */}
        <div className="grid grid-cols-[480px_1fr] gap-48 h-full ">
          <SideNavigation />
          <main>
            <About />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}